apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mydockerapp-volume
  name: mydockerapp-volume
spec:
  storageClassName: mysql-database-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
      
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-database-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
